### ISSUE TITLE
switch from blitzar to jsonforms

### ISSUE THREAD

**Issue by mgineer85** [photobooth-app/photobooth-frontend#11]
removing the non-maintained blitzar and implementing jsonforms.
allows to reuse the quasar components better and create nested layouts which could be useful to add lists of collages.

- working on this here: https://github.com/photobooth-app/photobooth-frontend/tree/jsonforms
- reference implementation for vuetify: https://github.com/eclipsesource/jsonforms-vuetify-renderers/blob/vue3/vue-vuetify/src/controls/BooleanToggleControlRenderer.vue
- reference implementation native html5 elements: https://github.com/eclipsesource/jsonforms/blob/master/packages/vue-vanilla/src/controls/NumberControlRenderer.vue
- documentation: https://jsonforms.io/docs/uischema/controls

**Comment by DominicWindisch** [comment]
Current progress looks like a hell of a lot of work. Hat's off!

![](https://www.reactiongifs.com/wp-content/uploads/2013/03/thumbs-aloft.gif)

**Comment by mgineer85** [comment]
transition to jsonforms is final.
all controls render correctly now again.
still needs tweaking but the actual transition is finished.
