### ISSUE TITLE
Printing of collages disabled

### ISSUE THREAD

**Issue by OpenLarry** [photobooth-app/photobooth-frontend#13]
Hi!

First of all, thank you for this great project and all the effort!

Shouldn't this array https://github.com/photobooth-app/photobooth-frontend/blob/09124a24d05b9dfc35d9d2cd1c293a9187d27fd5/src/components/GalleryImageDetail.vue#L453 also include `collage`? Otherwise, printing of collages is not possible and the button is grayed out.

**Comment by mgineer85** [comment]
You are right. Printing collages is possible, apply additional filter not. 
Fix will be included in next release.
Thx for reporting!
